import "../styles/globals.css";
import Header from "./header";
import { ContextProvider } from "../components/Clients";

export const metadata = {
  title: "Booking App",
  description: "Booking App Generated by Next.js",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <ContextProvider>
          <>
            <Header />
            {children}
          </>
        </ContextProvider>
      </body>
    </html>
  );
}
