"use client";

import { redirect } from "next/navigation";
import Link from "next/link";
import React, { useContext, useState } from "react";
import { toast } from "react-hot-toast";
import { Context } from "../../components/Clients";

const Page = () => {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const { user, setUser } = useContext(Context);

  const registerHandler = async (e) => {
    e.preventDefault();

    try {
      const res = await fetch("/api/auth/register", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name,
          email,
          password,
        }),
      });

      const data = await res.json();
      if (!data.success) return toast.error(data.message);
      setUser(data.user);
      toast.success(data.message);
    } catch (error) {
      return toast.error(error);
    }
  };

  if (user._id) return redirect("/");

  return (
    <div className="flex justify-center items-center">
      <section>
        <form
          onSubmit={registerHandler}
          className="flex flex-col justify-center items-center"
        >
          <input
            onChange={(e) => setName(e.target.value)}
            value={name}
            type="text"
            placeholder="Enter Name"
            className="h-12 w-96 m-4 p-4 border border-black rounded"
          />
          <input
            onChange={(e) => setEmail(e.target.value)}
            value={email}
            type="email"
            placeholder="Enter Email"
            className="h-12 w-96 m-4 p-4 border border-black rounded"
          />
          <input
            onChange={(e) => setPassword(e.target.value)}
            value={password}
            type="password"
            placeholder="Enter Password"
            className="h-12 w-96 m-4 p-4 border border-black rounded"
          />
          <button type="submit" className="btn-primary ">
            Sign Up
          </button>
          <p>OR</p>
          <Link href={"/login"} className="btn-secondary ">
            Log In
          </Link>
        </form>
      </section>
    </div>
  );
};

// export const metadata = {
//   title: "Register - Booking App",
//   description: "Booking App Generated by Next.js",
// };

export default Page;
