"use client";

import Link from "next/link";
import React, { useContext, useState } from "react";
import { Context } from "../../components/Clients";
import { redirect } from "next/navigation";
import { toast } from "react-hot-toast";

const Page = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const { user, setUser } = useContext(Context);

  const loginHandler = async (e) => {
    e.preventDefault();

    try {
      const res = await fetch("/api/auth/login", {
        method: "POST",
        body: JSON.stringify({
          email,
          password,
        }),
        headers: {
          "Content-Type": "application/json",
        },
      });
      const data = await res.json();
      if (!data.success) return toast.error(data.message);
      setUser(data.user);
      toast.success(data.message);
    } catch (error) {
      return toast.error(error);
    }
  };

  if (user._id) return redirect("/");

  return (
    <div className="flex justify-center items-center">
      <section>
        <form
          onSubmit={loginHandler}
          className="flex flex-col justify-center items-center"
        >
          <input
            onChange={(e) => setEmail(e.target.value)}
            value={email}
            type="email"
            placeholder="Enter Email"
            className="h-12 w-96 m-4 p-4 border border-black rounded"
          />
          <input
            onChange={(e) => setPassword(e.target.value)}
            value={password}
            type="password"
            placeholder="Enter Password"
            className="h-12 w-96 m-4 p-4 border border-black rounded"
          />
          <button type="submit" className="btn-primary ">
            Login
          </button>
          <p>OR</p>
          <Link href={"/register"} className="btn-secondary ">
            New user
          </Link>
        </form>
      </section>
    </div>
  );
};

// export const metadata = {
//   title: "Login - Booking App",
//   description: "Booking App Generated by Next.js",
// };

export default Page;
