"use client"

import React from "react";
import Link from "next/link";

const page = () => {
  return (
    <div className="flex justify-center items-center">
      <section>
        <form action="" className="flex flex-col justify-center items-center">
          <input
            type="email"
            placeholder="Enter Email"
            className="h-12 w-96 m-4 p-4 border border-black rounded"
          />
          <input
            type="password"
            placeholder="Enter password"
            className="h-12 w-96 m-4 p-4 border border-black rounded"
          />
          <button
            type="submit"
            className="btn-primary "
          >
            Login
          </button>
          <p>OR</p>
          <Link
            href={"/register"}
            className="btn-secondary "
          >
            New user
          </Link>
        </form>
      </section>
    </div>
  );
};

// export const metadata = {
//   title: "Login - Booking App",
//   description: "Booking App Generated by Next.js",
// };

export default page;
